language: python
python:
  - "2.7"
sudo: false
addons:
  apt:
    packages:
      - texlive
      - dvipng
      - texlive-latex-extra
      # - libhdf5-serial-dev # headers for h5py
before_install:
  # Getting scipy/numpy from Miniconda speeds up Travis builds,
  # see https://gist.github.com/dan-blanchard/7045057
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # See http://ryanvarley.uk/solutions/2014/05/14/
  # how-to-solve-travis-ci-matplotlib-tclerror-no-display/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose sympy mpi4py pandas pyyaml
  - wget http://bionetgen.googlecode.com/files/BioNetGen-2.2.5-stable.zip
  - unzip BioNetGen-2.2.5-stable.zip
  - export BNGPATH=`pwd`/BioNetGen-2.2.5-stable
  - pip install git+https://github.com/pysb/pysb.git
  # Patched branch of emcee
  - pip install git+https://github.com/johnbachman/emcee.git
  - pip install triangle-plot
  - pip install openpyxl
  - pip install sphinx 
  # Make the results directory
  - mkdir -p results/figures/panels
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  # Misc dependencies
  #- pip install cython # needed by h5py
  #- pip install h5py
script: ./run_tests.sh
