language: python
python:
  - "2.7"
sudo: false
addons:
  apt:
    packages:
      - openmpi-bin
      - openmpi-dev
      - texlive
      - dvipng
      - texlive-latex-extra
      # - libhdf5-serial-dev # headers for h5py
#before_install:
#  - sudo apt-get install python-scipy
#  - sudo apt-get install openmpi-bin openmpi-dev
#  # Install TeX for plotting
#  - sudo apt-get install texlive
#  - sudo apt-get install dvipng
#  - sudo apt-get install texlive-latex-extra
before_install:
  # Getting scipy/numpy from Miniconda speeds up Travis builds,
  # see https://gist.github.com/dan-blanchard/7045057
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # See http://ryanvarley.uk/solutions/2014/05/14/
  # how-to-solve-travis-ci-matplotlib-tclerror-no-display/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose sympy mpi4py pandas pyyaml openpyxl
  - wget http://bionetgen.googlecode.com/files/BioNetGen-2.2.5-stable.zip
  - unzip BioNetGen-2.2.5-stable.zip
  - export BNGPATH=`pwd`/BioNetGen-2.2.5-stable
  - pip install git+https://github.com/pysb/pysb.git
  - pip install git+https://github.com/johnbachman/emcee.git
  - pip install triangle-plot
  - mkdir -p results/figures/panels
  - export PYTHONPATH=$PYTHONPATH:.

  #- wget http://bionetgen.googlecode.com/files/BioNetGen-2.2.5-stable.zip
  #- unzip BioNetGen-2.2.5-stable.zip
  #- sudo ln -s `pwd`/BioNetGen-2.2.5-stable /usr/local/share/BioNetGen
  # Misc dependencies
  #- pip install matplotlib
  #- pip install pyyaml
  #- pip install mpi4py
  #- pip install pandas
  #
  #- pip install cython # needed by h5py
  #- pip install h5py
  # Install the nose-exclude plugin allowing us to ignore dirs
  #- pip install nose-exclude
  # Patched branch of emcee
  # Make the results directory
script: ./run_tests.sh
