FIGDIR := results/figures
DATADIR := tbidbaxlipo/data
CODEDIR := tbidbaxlipo

figures: \
		$(FIGDIR)/fig_141016_1.pdf \
		$(FIGDIR)/fig_fmax_fit_comparison.pdf \
		$(FIGDIR)/poisson_bax_fmax.pdf

clean:
	cd $(FIGDIR); rm -f *.pdf

# Bax depletion figures
# fig_141016_1.pdf, fig_141016_2.pdf
$(FIGDIR)/fig_141016_1.pdf: \
		$(DATADIR)/141016_Bax_depletion_preincubation.txt \
		$(DATADIR)/141016_Bax_depletion_timecourse.txt \
		$(DATADIR)/141016_Bax_depletion_triton.txt \
		$(DATADIR)/141016_Bax_depletion_added_ANTS_EF.txt \
		$(CODEDIR)/util/plate_assay.py \
		$(CODEDIR)/util/__init__.py \
		$(CODEDIR)/plots/layout_141016.py
	python $(CODEDIR)/plots/layout_141016.py
	mv *.pdf $(FIGDIR)

# Figs generated by hazard_rate.py
# fig_fmax_fit_comparison.pdf, fig_hazard_rate.pdf
$(FIGDIR)/fig_fmax_fit_comparison.pdf: \
		$(CODEDIR)/plots/layout_140311.py \
		$(CODEDIR)/plots/hazard_rate.py \
		$(CODEDIR)/util/__init__.py \
		$(CODEDIR)/util/fitting.py
	python $(CODEDIR)/plots/hazard_rate.py
	mv *.pdf $(FIGDIR)

# Figures showing the relationship between Bax distribution and fraction
# permeabilized
# poisson_bax_fmax.pdf, poisson_bax_fmax_fit.pdf
$(FIGDIR)/poisson_bax_fmax.pdf: \
		$(CODEDIR)/plots/poisson_bax_fmax.py
	python $(CODEDIR)/plots/poisson_Bax_fmax.py
	mv *.pdf $(FIGDIR)

