FIGDIR := results/figures
DATADIR := tbidbaxlipo/data
CODEDIR := tbidbaxlipo
MCMCDIR := results/mcmc

figures: \
		$(FIGDIR)/fig_141016_1.pdf \
		$(FIGDIR)/fig_fmax_fit_comparison.pdf \
		$(FIGDIR)/poisson_bax_fmax.pdf \
		$(FIGDIR)/pt_140318_nbd_2_conf_fits.pdf \
		$(FIGDIR)/140429_exact_comp_bind_fit.pdf

clean:
	cd $(FIGDIR); rm -f *.pdf

# --- Bax depletion figures ----
# fig_141016_1.pdf, fig_141016_2.pdf
$(FIGDIR)/fig_141016_1.pdf: \
		$(DATADIR)/141016_Bax_depletion_preincubation.txt \
		$(DATADIR)/141016_Bax_depletion_timecourse.txt \
		$(DATADIR)/141016_Bax_depletion_triton.txt \
		$(DATADIR)/141016_Bax_depletion_added_ANTS_EF.txt \
		$(CODEDIR)/util/plate_assay.py \
		$(CODEDIR)/util/__init__.py \
		$(CODEDIR)/plots/layout_141016.py
	python $(CODEDIR)/plots/layout_141016.py
	mv *.pdf $(FIGDIR)

# --- Figs generated by hazard_rate.py ----
# fig_fmax_fit_comparison.pdf, fig_hazard_rate.pdf
$(FIGDIR)/fig_fmax_fit_comparison.pdf: \
		$(CODEDIR)/plots/layout_140311.py \
		$(CODEDIR)/plots/hazard_rate.py \
		$(CODEDIR)/util/__init__.py \
		$(CODEDIR)/util/fitting.py
	python $(CODEDIR)/plots/hazard_rate.py
	mv *.pdf $(FIGDIR)

# --- Figures showing the relationship between Bax distribution and fraction
#     permeabilized ----
# poisson_bax_fmax.pdf, poisson_bax_fmax_fit.pdf
$(FIGDIR)/poisson_bax_fmax.pdf: \
		$(CODEDIR)/plots/poisson_bax_fmax.py
	python $(CODEDIR)/plots/poisson_bax_fmax.py
	mv *.pdf $(FIGDIR)

# --- Fits of models to 140318 Bax-NBD/liposome titration data by MCMC ----
# Makes plots pt..._fits.pdf, pt..._tri.pdf
# (for 2_conf, 2_conf_rev, and 3_conf models)
$(FIGDIR)/pt_140318_nbd_2_conf_fits.pdf: \
		$(CODEDIR)/pt/pck/pt_140318_nbd_2_conf_5.pck \
		$(CODEDIR)/pt/pck/pt_140318_nbd_2_conf_rev_4.pck \
		$(CODEDIR)/pt/pck/pt_140318_nbd_3_conf_3.pck \
		$(CODEDIR)/plots/layout_140318.py
	python $(CODEDIR)/plots/layout_140318.py \
			$(CODEDIR)/pt/pck/pt_140318_nbd_2_conf_5.pck pt_140318_nbd_2_conf
	python $(CODEDIR)/plots/layout_140318.py \
			$(CODEDIR)/pt/pck/pt_140318_nbd_2_conf_rev_4.pck pt_140318_nbd_2_conf_rev
	python $(CODEDIR)/plots/layout_140318.py \
			$(CODEDIR)/pt/pck/pt_140318_nbd_3_conf_3.pck pt_140318_nbd_3_conf
	mv *.pdf $(FIGDIR)

# --- Fits of 140429 Bid FRET competition experiment by MCMC to the exact
#     competition binding model ----
# Files: 140429_exact_comp_bind_fit.pdf, 140429_exact_comp_bind_marginals.pdf
$(FIGDIR)/140429_exact_comp_bind_fit.pdf: \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/exact_comp_bind_mcmc.py \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/calculate_fret.py \
		$(CODEDIR)/data/parse_140429_Bid_membrane_FRET.py \
		$(CODEDIR)/data/140429_Bid_membrane_FRET.xlsx \
		$(CODEDIR)/util/__init__.py \
		$(MCMCDIR)/140429_exact_comp_bind_mcmc.pck
	python $(CODEDIR)/plots/x140429_Bid_membrane_FRET/exact_comp_bind_mcmc.py plot $(MCMCDIR)/140429_exact_comp_bind_mcmc.pck
	mv *.pdf $(FIGDIR)

$(MCMCDIR)/140429_exact_comp_bind_mcmc.pck: \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/exact_comp_bind_mcmc.py \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/calculate_fret.py \
		$(CODEDIR)/data/parse_140429_Bid_membrane_FRET.py \
		$(CODEDIR)/data/140429_Bid_membrane_FRET.xlsx
	echo "Exiting, must remake:"
	echo $@
	exit 1




