FIGDIR := results/figures
DATADIR := tbidbaxlipo/data
CODEDIR := tbidbaxlipo
MCMCDIR := results/mcmc
PQUEUE := sorger_par_unlimited

x140320 := $(CODEDIR)/plots/x140320_NBD_Bax_BimBH3_unlab_Bax_titration/mcmc

figures: \
		$(FIGDIR)/fig_141016_1.pdf \
		$(FIGDIR)/fig_fmax_fit_comparison.pdf \
		$(FIGDIR)/poisson_bax_fmax.pdf \
		$(FIGDIR)/pt_140318_nbd_2_conf_fits.pdf \
		$(FIGDIR)/slice_bax_fixed.pdf \
		$(FIGDIR)/140320_exp_fits.pdf \
		$(FIGDIR)/140318_exp_fits_lstsq_fmax_var.pdf \
		$(FIGDIR)/140429_exact_comp_bind_fit.pdf \
		$(FIGDIR)/140429_gouy_chap_fit.pdf

clean:
	cd $(FIGDIR); rm -f *.pdf

# This bit here allows us to only rebuild when the hash of a file changes.
# See blog post describing the approach here:
# http://blog.jgc.org/2006/04/rebuilding-when-hash-has-changed-not.html
to-md5 = $(patsubst %,%.md5,$1)
from-md5 = $(patsubst %.md5,%,$1)

# The .md5 file is updated only if the hash has changed
%.md5: FORCE
	@$(if $(filter-out $(shell cat $@ 2>/dev/null), $(shell md5sum $*)),md5sum $* > $@)

# Dummy target so the .md5 step is always run
FORCE:

# Keying the MCMC execution on the dependency file ensures that a re-run is
# performed if the model ensemble specification (or fit parameters) has
# changed. Also ensures that the dependency file exists before we try to
# include it. As a convention, the target used here should correspond to the
# basename of the .yaml file specifying the fit for the model ensemble
# (e.g., pt_140320.yaml --> pt_140320)
pt_140320: $(x140320)/pt_140320.deps.txt
# This file specifies the list of *.mcmc files that pt_140320 depends on
-include $(x140320)/pt_140320.deps.txt

# Running this script generates both the dependency list and the .yaml files
# specifying the fit parameters for each individual model
%.deps.txt: %.fit.ensemble
	python -m tbidbaxlipo.pt.generate_model_ensemble_fit_files $<

# In this case, we know that the .yaml file exists, since it has been
# regenerated in the step that regenerated the dependency file. What
# we care about is whether the hash is any different.
%.mcmc: $(call to-md5, %.fit)
	python -m tbidbaxlipo.pt.compile_models $(call from_md5, $<)
	bsub -q $(PQUEUE) -n 50 -W 12:00 -a openmpi mpirun.lsf python -m tbidbaxlipo.pt.run_pt $(call from-md5, $<) 1

# Don't delete the .md5 files! Without this rule they are treated as
# intermediates and deleted.
.PRECIOUS: %.md5

# --- Bax depletion figures ----
# fig_141016_1.pdf, fig_141016_2.pdf
$(FIGDIR)/fig_141016_1.pdf: \
		$(DATADIR)/141016_Bax_depletion_preincubation.txt \
		$(DATADIR)/141016_Bax_depletion_timecourse.txt \
		$(DATADIR)/141016_Bax_depletion_triton.txt \
		$(DATADIR)/141016_Bax_depletion_added_ANTS_EF.txt \
		$(CODEDIR)/util/plate_assay.py \
		$(CODEDIR)/util/__init__.py \
		$(CODEDIR)/plots/layout_141016.py
	python $(CODEDIR)/plots/layout_141016.py
	mv *.pdf $(FIGDIR)

# --- Figs generated by hazard_rate.py ----
# fig_fmax_fit_comparison.pdf, fig_hazard_rate.pdf
$(FIGDIR)/fig_fmax_fit_comparison.pdf: \
		$(CODEDIR)/plots/layout_140311.py \
		$(CODEDIR)/plots/hazard_rate.py \
		$(CODEDIR)/util/__init__.py \
		$(CODEDIR)/util/fitting.py
	python $(CODEDIR)/plots/hazard_rate.py
	mv *.pdf $(FIGDIR)

# --- Figures showing the relationship between Bax distribution and fraction
#     permeabilized ----
# poisson_bax_fmax.pdf, poisson_bax_fmax_fit.pdf
$(FIGDIR)/poisson_bax_fmax.pdf: \
		$(CODEDIR)/plots/poisson_bax_fmax.py
	python $(CODEDIR)/plots/poisson_bax_fmax.py
	mv *.pdf $(FIGDIR)

# --- Fits of models to 140318 Bax-NBD/liposome titration data by MCMC ----
# Makes plots pt..._fits.pdf, pt..._tri.pdf
# (for 2_conf, 2_conf_rev, and 3_conf models)
$(FIGDIR)/pt_140318_nbd_2_conf_fits.pdf: \
		$(CODEDIR)/plots/x140318_Bax_liposome_titration/pt_140318_nbd_2_conf_5.mcmc \
		$(CODEDIR)/plots/x140318_Bax_liposome_titration/pt_140318_nbd_2_conf_rev_4.mcmc \
		$(CODEDIR)/plots/x140318_Bax_liposome_titration/pt_140318_nbd_3_conf_3.mcmc \
		$(CODEDIR)/plots/x140318_Bax_liposome_titration/plot_mcmc_model_fits.py
	python $(CODEDIR)/plots/x140318_Bax_liposome_titration/plot_mcmc_model_fits.py \
			$(CODEDIR)/plots/x140318_Bax_liposome_titration/pt_140318_nbd_2_conf_5.mcmc pt_140318_nbd_2_conf
	python $(CODEDIR)/plots/x140318_Bax_liposome_titration/plot_mcmc_model_fits.py \
			$(CODEDIR)/plots/x140318_Bax_liposome_titration/pt_140318_nbd_2_conf_rev_4.mcmc pt_140318_nbd_2_conf_rev
	python $(CODEDIR)/plots/x140318_Bax_liposome_titration/plot_mcmc_model_fits.py \
			$(CODEDIR)/plots/x140318_Bax_liposome_titration/pt_140318_nbd_3_conf_3.mcmc pt_140318_nbd_3_conf
	mv *.pdf $(FIGDIR)

# --- Slice diagrams ---
$(FIGDIR)/slice_bax_fixed.pdf: \
		$(CODEDIR)/plots/slice_diagrams.py \
		$(CODEDIR)/util/__init__.py
	python $(CODEDIR)/plots/slice_diagrams.py
	mv *.pdf $(FIGDIR)

# --- Exponential fits to Bax titration, 140320
#     140320_exp_fit_curves.pdf, 140320_exp_fits.pdf ---
$(FIGDIR)/140320_exp_fits.pdf: \
		$(CODEDIR)/plots/x140320_NBD_Bax_BimBH3_unlab_Bax_titration/preprocess_data.py \
		$(CODEDIR)/plots/x140320_NBD_Bax_BimBH3_unlab_Bax_titration/exp_fits_lstsq.py \
		$(CODEDIR)/data/140320_NBD_Bax_BimBH3_unlab_Bax_titration.txt \
		$(CODEDIR)/util/fitting.py \
		$(CODEDIR)/util/plate_assay.py \
		$(CODEDIR)/util/__init__.py
	python $(CODEDIR)/plots/x140320_NBD_Bax_BimBH3_unlab_Bax_titration/exp_fits_lstsq.py
	mv *.pdf $(FIGDIR)

# --- 140318_exp_fits_lstsq_fmax_var.pdf,
#     140318_exp_fits_lstsq_curves_fmax_var.pdf,
#     140318_exp_fits_lstsq_fmax_fixed.pdf,
#     140318_exp_fits_lstsq_curves_fmax_fixed.pdf ---
$(FIGDIR)/140318_exp_fits_lstsq_fmax_var.pdf: \
		$(CODEDIR)/plots/x140318_Bax_liposome_titration/exp_fits_lstsq.py \
		$(CODEDIR)/plots/x140318_Bax_liposome_titration/preprocess_data.py \
		$(CODEDIR)/util/plate_assay.py \
		$(CODEDIR)/data/140318_NBD_Bax_BimBH3_lipo_titration.txt \
		$(CODEDIR)/util/__init__.py
	python $(CODEDIR)/plots/x140318_Bax_liposome_titration/exp_fits_lstsq.py
	mv *.pdf $(FIGDIR)


# --- Fits of 140429 Bid FRET competition experiment by MCMC to the exact
#     competition binding model ----
# Files: 140429_exact_comp_bind_fit.pdf, 140429_exact_comp_bind_marginals.pdf
$(FIGDIR)/140429_exact_comp_bind_fit.pdf: \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/exact_comp_bind_mcmc.py \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/calculate_fret.py \
		$(CODEDIR)/data/parse_140429_Bid_membrane_FRET.py \
		$(CODEDIR)/data/140429_Bid_membrane_FRET.xlsx \
		$(CODEDIR)/util/__init__.py \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/140429_exact_comp_bind.mcmc
	python $(CODEDIR)/plots/x140429_Bid_membrane_FRET/exact_comp_bind_mcmc.py plot \
		   $(CODEDIR)/plots/x140429_Bid_membrane_FRET/140429_exact_comp_bind.mcmc
	mv *.pdf $(FIGDIR)

$(CODEDIR)/plots/x140429_Bid_membrane_FRET/140429_exact_comp_bind.mcmc: \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/exact_comp_bind_mcmc.py \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/calculate_fret.py \
		$(CODEDIR)/data/parse_140429_Bid_membrane_FRET.py \
		$(CODEDIR)/data/140429_Bid_membrane_FRET.xlsx
	bsub -q short -W 12:00 python $(CODEDIR)/plots/x140429_Bid_membrane_FRET/exact_comp_bind_mcmc.py sample $(CODEDIR)/plots/x140429_Bid_membrane_FRET/140429_exact_comp_bind.mcmc

# Files: 140429_gouy_chap_fit.pdf, 140429_gouy_chap_marginals.pdf
$(FIGDIR)/140429_gouy_chap_fit.pdf: \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/gouy_chap_mcmc.py \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/calculate_fret.py \
		$(CODEDIR)/data/parse_140429_Bid_membrane_FRET.py \
		$(CODEDIR)/data/140429_Bid_membrane_FRET.xlsx \
		$(CODEDIR)/util/__init__.py \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/140429_gouy_chap.mcmc
	python $(CODEDIR)/plots/x140429_Bid_membrane_FRET/gouy_chap_mcmc.py plot \
		   $(CODEDIR)/plots/x140429_Bid_membrane_FRET/140429_gouy_chap.mcmc
	mv *.pdf $(FIGDIR)

$(CODEDIR)/plots/x140429_Bid_membrane_FRET/140429_gouy_chap.mcmc: \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/gouy_chap_mcmc.py \
		$(CODEDIR)/plots/x140429_Bid_membrane_FRET/calculate_fret.py \
		$(CODEDIR)/data/parse_140429_Bid_membrane_FRET.py \
		$(CODEDIR)/data/140429_Bid_membrane_FRET.xlsx
	bsub -q short -W 12:00 python $(CODEDIR)/plots/x140429_Bid_membrane_FRET/gouy_chap_mcmc.py sample $(CODEDIR)/plots/x140429_Bid_membrane_FRET/140429_gouy_chap.mcmc

