bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 0 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 1 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 2 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 3 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 4 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 5 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 6 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 7 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 8 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 9 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 10 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 11 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 12 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 13 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 14 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 15 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 16 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 17 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 18 nbd_mcmc_linear
bsub -q sorger_1d python nbd_mcmc.py nbd_linear_random_initial_values.pck 19 nbd_mcmc_linear
